default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: msds_development

test:
  <<: *default
  database: msds_test

production:
  <<: *default
  database: msds_production
  username: msds
  password: <%= ENV['MSDS_DATABASE_PASSWORD'] %>
